### ISSUE TITLE
ApiCreateArtifactRequest only allows a body of type *os.File

### ISSUE THREAD

**Issue by acranbury** [Apicurio/apicurio-registry-client-sdk-go#17]
Multiple body types are supported by `setBody` called by `APIClient.prepareRequest`, but the top level `ApiCreateArtifactRequest.Body` only accepts `*os.File` rather than `interface{}`

**Comment by craicoverflow** [comment]
This is happening because the `FileContent` schema format is "binary" which OpenAPI Generator translates into `os.File`. ([see here](https://github.com/Apicurio/apicurio-registry/blob/master/app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json#L2783)) This is how OAS expects file uploads to be handled: https://swagger.io/docs/specification/describing-request-body/file-upload/

> Files use a type: string schema with format: binary or format: base64, depending on how the file contents will be encoded. For example:

`setBody` supports any type because it is generic and used by all API request methods which is why there is a difference in the types.

@EricWittmann what do you think? Are we expecting to be able to support non file uploads here? If so maybe the format should be changed in the OAS.

@acranbury As a workaround you could create a temporary file to put your contents into and use this to create the artifact?

**Comment by acranbury** [comment]
I've implemented the workaround and it's working for creation/deletion of artifacts, but I'm running into a similar issue for `GetArtifactVersion`. `GetArtifactVersionExecute` passes `&localVarReturnValue` which is a `***os.File` into `Client.decode`, which is looking for a `**os.File` instead.

Maybe binary `FileContent` is being incorrectly translated to `*os.File` rather than `os.File`?

**Comment by EricWittmann** [comment]
> Are we expecting to be able to support non file uploads here? If so maybe the format should be changed in the OAS.

Yeah I would expect we should support passing in the artifact content in any number of ways.  In java I would expect something like an `InputStream`.  Not sure what would make sense for Go.  Or alternatively having multiple variants of the same method that accept various types of inputs (string, file, etc).

I don't know enough about Go to comment on the `*os.File` vs `os.File` suggestion.

**Comment by acranbury** [comment]
I modified the source of `GetArtifactVersion` to return `*os.File` instead of the generated `**os.File` and it works as I expect. Without the modification I get back `nil` instead of anything useful.

**Comment by craicoverflow** [comment]
We're working on a solution to this currently, it might take a few days but hang tight! We really appreciate your feedback on this!

**Comment by matthyx** [comment]
Why not using an interface like `fs.file` which would allow to use something else than _real_ files?

**Comment by craicoverflow** [comment]
This SDK is generated automatically using the [OpenAPI Generator](https://openapi-generator.tech/) project. This maps `binary` types in OpenAPI to `os.File`. To fix that we would need to contribute a fix/improvement to this project or eject from their templates to go with our own. We have a fix in progress but it requires lots of testing to ensure backwards compatibility and we will also need to update other dependant projects.

**Comment by matthyx** [comment]
Awesome @craicoverflow let me know if I could help somehow. Good luck!

**Comment by craicoverflow** [comment]
Fix is out in [v0.4.0](https://github.com/Apicurio/apicurio-registry-client-sdk-go/releases/tag/v0.4.0)
